package com.az24.crawler.model;

public class CoursesLong {
	public int  id; 
	public int cat_id; 
	public String cat_title=""; 
	public int level_id; 
	public String title; 
	public String alias; 
	public String introtext=""; 
	public String content=""; 
	public String tags=""; 
	public String meta_keyword=""; 
	public String meta_title=""; 
	public String meta_description=""; 
	public int meta_noindex=0; 
	public int meta_nofollow=0; 
	public String picture=""; 
	public String youtube_link=""; 
	public String file_name=""; 
	public int c_type=1; 
	public int is_hot; 
	public int is_edit; 
	public int user_id; 
	public String username=""; 
	public int trainer_id; 
	public long create_date; 
	public long edit_date; 
	public long publish_date; 
	public long expired_date; 
	public long endvip_date; 
	public int time_show_vip; 
	public int status; 
	public float fee; 
	public String price=""; 
	public int degree; 
	public String degree_expand=""; 
	public int form_training; 
	public String form_training_expand=""; 
	public String form_enrollment=""; 
	public String string_time=""; 
	public String place=""; 
	public String profile=""; 
	public int start_date; 
	public int end_date; 
	public String info_expand=""; 
	public int admin_id; 
	public String  admin_name="";
	
	public String contact_name=""; 
	public String contact_email=""; 
	public String contact_tel=""; 
	public String contact_yahoo=""; 
	public String contact_skype=""; 
}
