package com.az24.crawler.store;

public class Store {
	public int id;
	public int user_id;
	public String name;
	public String title;
	public String logo;
	public String slogan;
	public String email;
	public String fax;
	public String mobile;
	public String tel;
	public String address;
	public String domain;
	public String website;
	public String area;
	public String store_alias;
	public String contact;
	public int province_id;
	public String province_code;
	public String province_name;
	public int status;
	public int active_mobile;
	public int is_store_warranty;
	public int type;
	public int month_extension;
	public int num_of_product;
	public int num_of_user_favourites;
	public int num_order_not_view;
	public int num_product_expire;
	public int num_product_to_expire;
	public int num_product_report_error;
	public int num_warning;
	public int exchange_rate;
	public int form_transport;
	public int product_policy;
	public int shipping_policy;
	public int payment_method;
	public int ordering_purchasing_policy;
	public int warranty_policy;
	public int basic_info;
	public String note;
	public String create_user;
	public long create_date;
	
	public String modify_user;
	public long modify_date;
	
	public long active_date;
	public long end_date;
	public int type_upgrade;
	public int rank;
	public String customer_care;
	public int type_menu;
	public long last_upgrade;
	public String xpath_price;
	public String price_type;
	public String xpath_exchange;
}
